version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch_local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=es-local-cluster
      - node.name=es-local-node
    ports:
      - "9205:9200"  # <--- changed external port to 9205
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana_local
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5605:5601"  # <--- changed external port to 5605
    depends_on:
      - elasticsearch
    networks:
      - es_network

volumes:
  es_data:

networks:
  es_network:
    driver: bridge
